"""TraCI manager for the Digital Twin SUMO sync pipeline.

Manages an independent SUMO instance (separate from the backend's
``sumo_service``) with vehicle lifecycle control: add, update, reroute,
remove.  Vehicles are injected dynamically — no route file needed.
"""

from __future__ import annotations

import logging
import os
import re
import sys
import tempfile
from pathlib import Path

from service.config import SUMO_HOME, SUMO_GUI
from service.network_gen import CENTER_JUNCTION

logger = logging.getLogger(__name__)

# Vehicle classes introduced after SUMO 1.18.0 (Debian Bookworm package).
# The net.xml files generated by SUMO 1.24.0 on Windows include these in
# disallow= attributes; SUMO 1.18.0 quits with "Unknown vehicle class" errors.
_UNSUPPORTED_VCLASSES: frozenset[str] = frozenset(
    {"container", "cable_car", "subway", "aircraft", "wheelchair", "scooter", "drone"}
)


def _patch_net_xml(src: Path) -> Path:
    """Write a temp copy of the net.xml with unsupported vClass names stripped."""
    content = src.read_text(encoding="utf-8", errors="replace")

    def _strip(m: re.Match) -> str:
        attr = m.group(1)
        classes = [c for c in m.group(2).split() if c not in _UNSUPPORTED_VCLASSES]
        return f'{attr}="{" ".join(classes)}"'

    patched = re.sub(r'\b((?:dis)?allow)="([^"]+)"', _strip, content)
    fd, tmp = tempfile.mkstemp(suffix=".net.xml")
    os.close(fd)
    Path(tmp).write_text(patched, encoding="utf-8")
    return Path(tmp)


# ── TraCI import ──────────────────────────────────────────────────────

_sumo_tools = os.path.join(SUMO_HOME, "tools")
if os.path.isdir(_sumo_tools) and _sumo_tools not in sys.path:
    sys.path.insert(0, _sumo_tools)

try:
    import traci  # type: ignore
    from traci.exceptions import TraCIException  # type: ignore
    TRACI_AVAILABLE = True
except ImportError:
    traci = None  # type: ignore
    TraCIException = Exception
    TRACI_AVAILABLE = False
    logger.warning("traci not available — SUMO sync disabled")

class SumoManager:
    """Manages a single headless SUMO instance for the sync pipeline.

    Each instance uses a unique TraCI connection label so multiple
    SUMO processes can run in parallel (e.g. RL + baseline).
    """

    def __init__(self, label: str = "digital_twin_sync") -> None:
        self._label = label
        self._running = False
        self._step_count = 0
        self._defined_routes: set[str] = set()
        self._patched_net: Path | None = None

    # ── Lifecycle ─────────────────────────────────────────────────────

    def start(self, network_path: str | Path, route_file: str | Path | None = None) -> None:
        """Start SUMO with the given network and optional route file."""
        if not TRACI_AVAILABLE:
            raise RuntimeError("traci is not available")
        if self._running:
            self.stop()

        binary = "sumo-gui" if SUMO_GUI else "sumo"
        sumo_bin = os.path.join(SUMO_HOME, "bin", binary)

        # Strip vehicle classes unknown to SUMO 1.18.0 from the network file
        src_net = Path(network_path)
        try:
            self._patched_net = _patch_net_xml(src_net)
            net_for_sumo = self._patched_net
            logger.info("Using patched net.xml: %s", net_for_sumo)
        except Exception as exc:
            logger.warning("Could not patch net.xml (%s) — using original", exc)
            self._patched_net = None
            net_for_sumo = src_net

        cmd = [
            sumo_bin,
            "-n", str(net_for_sumo),
            "--no-step-log", "true",
            "--no-warnings", "true",
            "--step-length", "1",
            "--time-to-teleport", "-1",  # disable teleporting
        ]

        if route_file and Path(route_file).exists():
            cmd.extend(["-r", str(route_file)])

        logger.info("Starting SUMO [%s]: %s", self._label, " ".join(cmd))
        traci.start(cmd, label=self._label)
        self._running = True
        self._step_count = 0
        self._defined_routes.clear()
        logger.info("SUMO [%s] started", self._label)

    def stop(self) -> None:
        """Close the SUMO connection."""
        if self._running:
            try:
                conn = traci.getConnection(self._label)
                conn.close()
            except Exception:
                pass
            self._running = False
            self._defined_routes.clear()
            logger.info("SUMO [%s] stopped (step %d)", self._label, self._step_count)
        if self._patched_net and self._patched_net.exists():
            self._patched_net.unlink(missing_ok=True)
            self._patched_net = None

    def step(self) -> dict:
        """Advance simulation by one step. Returns basic metrics."""
        conn = self._conn()
        conn.simulationStep()
        self._step_count += 1

        veh_ids = conn.vehicle.getIDList()
        total_wait = sum(conn.vehicle.getWaitingTime(v) for v in veh_ids)
        total_speed = sum(conn.vehicle.getSpeed(v) for v in veh_ids)
        n = len(veh_ids)

        return {
            "step": self._step_count,
            "num_vehicles": n,
            "total_waiting_time": total_wait,
            "avg_waiting_time": total_wait / n if n else 0.0,
            "avg_speed": total_speed / n if n else 0.0,
            "arrived": conn.simulation.getArrivedNumber(),
        }

    @property
    def running(self) -> bool:
        return self._running

    @property
    def step_count(self) -> int:
        return self._step_count

    # ── Vehicle management ────────────────────────────────────────────

    def add_vehicle(
        self,
        veh_id: str,
        route: list[str] | str,
        lane_index: int = 0,
        pos: float = 0.1,
        speed: float = 0.0,
    ) -> bool:
        """Add a vehicle to the simulation. Returns True on success."""
        conn = self._conn()

        if isinstance(route, list):
            # Ensure a route exists for this edge sequence
            route_id = "_".join(route)
            if route_id not in self._defined_routes:
                try:
                    conn.route.add(route_id, route)
                    self._defined_routes.add(route_id)
                except TraCIException:
                    self._defined_routes.add(route_id)
        else:
            route_id = route

        try:
            conn.vehicle.add(
                veh_id,
                routeID=route_id,
                departLane=str(lane_index),
                departPos=str(pos),
                departSpeed=str(speed),
            )
            return True
        except TraCIException as exc:
            logger.debug("Failed to add vehicle %s: %s", veh_id, exc)
            return False

    def update_vehicle_speed(self, veh_id: str, speed: float) -> None:
        """Set a vehicle's speed (-1 to release to SUMO control)."""
        conn = self._conn()
        try:
            conn.vehicle.setSpeed(veh_id, speed)
        except TraCIException:
            pass  # vehicle may have left

    def reroute_vehicle(self, veh_id: str, route_or_edge: list[str] | str) -> bool:
        """Change a vehicle's route or target edge. Returns True on success."""
        conn = self._conn()

        if isinstance(route_or_edge, list):
            # Ensure route is defined
            route_id = "_".join(route_or_edge)
            if route_id not in self._defined_routes:
                try:
                    conn.route.add(route_id, route_or_edge)
                    self._defined_routes.add(route_id)
                except TraCIException:
                    self._defined_routes.add(route_id)

            try:
                conn.vehicle.setRoute(veh_id, route_or_edge)
                return True
            except TraCIException as exc:
                logger.debug("Failed to setRoute for %s: %s", veh_id, exc)
                return False
        else:
            # Single edge ID -> changeTarget
            try:
                conn.vehicle.changeTarget(veh_id, route_or_edge)
                return True
            except TraCIException as exc:
                logger.debug("Failed to changeTarget for %s: %s", veh_id, exc)
                return False

    def remove_vehicle(self, veh_id: str) -> None:
        """Remove a vehicle from the simulation."""
        conn = self._conn()
        try:
            conn.vehicle.remove(veh_id)
        except TraCIException:
            pass

    def get_vehicle_ids(self) -> list[str]:
        """Return IDs of all vehicles currently in the simulation."""
        conn = self._conn()
        return list(conn.vehicle.getIDList())

    def get_traffic_light_ids(self) -> list[str]:
        """Return all traffic light IDs in the network."""
        conn = self._conn()
        return list(conn.trafficlight.getIDList())

    def get_vehicles(self) -> list[dict]:
        """Return detailed state of all vehicles."""
        conn = self._conn()
        result = []
        for vid in conn.vehicle.getIDList():
            pos = conn.vehicle.getPosition(vid)
            result.append({
                "id": vid,
                "x": pos[0],
                "y": pos[1],
                "speed": conn.vehicle.getSpeed(vid),
                "waiting_time": conn.vehicle.getWaitingTime(vid),
                "lane": conn.vehicle.getLaneID(vid),
                "route": list(conn.vehicle.getRoute(vid)),
            })
        return result

    # ── Traffic light control ─────────────────────────────────────────

    def get_tl_id(self) -> str:
        """Return the traffic light ID (assumes single junction)."""
        conn = self._conn()
        tls = conn.trafficlight.getIDList()
        if not tls:
            raise RuntimeError("No traffic lights in the network")
        return tls[0]

    def get_all_tl_ids(self) -> list[str]:
        """Return all traffic light IDs in the network."""
        conn = self._conn()
        return list(conn.trafficlight.getIDList())

    def get_all_traffic_light_states(self) -> dict[str, dict]:
        """Query current TL state for ALL traffic lights in the network."""
        conn = self._conn()
        result = {}
        for tl_id in conn.trafficlight.getIDList():
            result[tl_id] = {
                "tl_id": tl_id,
                "phase": conn.trafficlight.getPhase(tl_id),
                "state": conn.trafficlight.getRedYellowGreenState(tl_id),
                "program": conn.trafficlight.getProgram(tl_id),
            }
        return result

    def install_fixed_time_on_all(
        self,
        green_duration: int = 33,
        yellow_duration: int = 3,
        red_duration: int = 30,
        exclude_tl_ids: list[str] | None = None,
    ) -> list[str]:
        """Install fixed-time TLS programs on ALL traffic lights, excluding specified ones.

        Fixed timing: green_duration green - yellow_duration yellow - red_duration red per direction.
        Returns list of TL IDs that were configured.
        """
        conn = self._conn()
        exclude = set(exclude_tl_ids or [])
        configured = []

        for tl_id in conn.trafficlight.getIDList():
            if tl_id in exclude:
                continue

            try:
                current = conn.trafficlight.getAllProgramLogics(tl_id)
                if not current:
                    continue

                num_links = len(current[0].phases[0].state)
                half = num_links // 2

                # Phase 0: first half green, second half red
                ns_green = "G" * half + "r" * (num_links - half)
                ns_yellow = "y" * half + "r" * (num_links - half)
                # Phase 2: first half red, second half green
                ew_green = "r" * half + "G" * (num_links - half)
                ew_yellow = "r" * half + "y" * (num_links - half)

                phases = [
                    traci.trafficlight.Phase(green_duration, ns_green),
                    traci.trafficlight.Phase(yellow_duration, ns_yellow),
                    traci.trafficlight.Phase(red_duration, ew_green),
                    traci.trafficlight.Phase(yellow_duration, ew_yellow),
                ]

                logic = traci.trafficlight.Logic(
                    "fixed_baseline", 0, 0, phases=phases,
                )

                conn.trafficlight.setProgramLogic(tl_id, logic)
                conn.trafficlight.setProgram(tl_id, "fixed_baseline")
                configured.append(tl_id)
            except Exception as exc:
                logger.debug("Failed to install fixed-time on %s: %s", tl_id, exc)

        logger.info(
            "Installed fixed-time (%ds green / %ds yellow / %ds red) on %d TLs (excluded %d)",
            green_duration, yellow_duration, red_duration,
            len(configured), len(exclude),
        )
        return configured

    def build_observation_for_tl(
        self,
        tl_id: str,
        num_actions: int,
        max_lanes: int | None = None,
        elapsed_in_green: int = 0,
        max_bucket: float = 40.0,
    ) -> list[float]:
        """Build an observation vector for a specific traffic light.

        Observation = [lane_vehicle_counts (padded to max_lanes), phase_one_hot, elapsed_scalar]
        Matches the CoLight training environment's observation format (ob_length = max_lanes + num_actions + 1).

        Args:
            tl_id: Traffic light ID.
            num_actions: Number of actions (= num_actions from model).
            max_lanes: Pad lane counts to this length. If None, no padding is applied.
            elapsed_in_green: Steps elapsed in the current green phase (for duration mode).
            max_bucket: Largest duration bucket in seconds (default 40 for DURATION_BUCKETS_SEC).
        """
        conn = self._conn()
        controlled_lanes = list(conn.trafficlight.getControlledLanes(tl_id))

        # Deduplicate while preserving order
        seen = set()
        unique_lanes = []
        for lane in controlled_lanes:
            if lane not in seen:
                seen.add(lane)
                unique_lanes.append(lane)

        lane_counts = []
        for lane in unique_lanes:
            try:
                lane_counts.append(float(conn.lane.getLastStepVehicleNumber(lane)))
            except Exception:
                lane_counts.append(0.0)

        # Pad to max_lanes so all TLs produce the same-length observation
        if max_lanes is not None and len(lane_counts) < max_lanes:
            lane_counts += [0.0] * (max_lanes - len(lane_counts))
        elif max_lanes is not None:
            lane_counts = lane_counts[:max_lanes]

        try:
            sumo_phase = conn.trafficlight.getPhase(tl_id)
        except Exception:
            sumo_phase = 0

        # Get green phase indices
        logic = conn.trafficlight.getAllProgramLogics(tl_id)
        green_indices = []
        if logic:
            phases = logic[0].phases
            green_indices = [i for i, p in enumerate(phases) if "G" in p.state or "g" in p.state]

        current_green_idx = 0
        if green_indices and sumo_phase in green_indices:
            current_green_idx = green_indices.index(sumo_phase)

        phase_one_hot = [0.0] * num_actions
        if 0 <= current_green_idx < num_actions:
            phase_one_hot[current_green_idx] = 1.0

        # Elapsed scalar matches CoLight ob format: elapsed / max_bucket, clamped to [0, 1]
        elapsed_scalar = [min(float(elapsed_in_green) / max_bucket, 1.0)]

        return lane_counts + phase_one_hot + elapsed_scalar

    def _resolve_tl_id(self, tl_id: str | None) -> str:
        return tl_id or self.get_tl_id()

    def get_traffic_light_state(self, tl_id: str | None = None) -> dict:
        """Query current TL state."""
        conn = self._conn()
        tl_id = self._resolve_tl_id(tl_id)
        return {
            "tl_id": tl_id,
            "phase": conn.trafficlight.getPhase(tl_id),
            "state": conn.trafficlight.getRedYellowGreenState(tl_id),
            "program": conn.trafficlight.getProgram(tl_id),
        }

    def set_traffic_light_phase(self, phase_index: int, tl_id: str | None = None) -> None:
        """Set the traffic light to a specific phase."""
        conn = self._conn()
        tl_id = self._resolve_tl_id(tl_id)
        conn.trafficlight.setPhase(tl_id, phase_index)

    def get_controlled_lanes(self, tl_id: str | None = None) -> list[str]:
        """Return the list of lanes controlled by the traffic light."""
        conn = self._conn()
        tl_id = self._resolve_tl_id(tl_id)
        return list(conn.trafficlight.getControlledLanes(tl_id))

    def get_tl_link_metadata(self, tl_id: str) -> dict:
        """Map SUMO state-string indices to physical approaches.

        Each char in the SUMO state string controls one link (a from-lane →
        to-lane connection). Multiple links share an incoming edge — those
        belong to the same physical approach. This method groups state-string
        indices by source edge and computes each approach's compass angle
        from the edge's last-segment direction toward the junction.

        Returns ``{"approaches": [{"angle_deg": float, "link_indices": [int,...], "from_edge": str}, ...]}``
        with approaches sorted clockwise from north.
        """
        import math
        conn = self._conn()
        try:
            controlled_links = conn.trafficlight.getControlledLinks(tl_id)
        except Exception:
            return {"approaches": []}

        edge_to_indices: dict[str, list[int]] = {}
        edge_to_first_lane: dict[str, str] = {}
        for state_idx, link_tuples in enumerate(controlled_links):
            if not link_tuples:
                continue
            try:
                from_lane = link_tuples[0][0]
                from_edge = conn.lane.getEdgeID(from_lane)
            except Exception:
                continue
            edge_to_indices.setdefault(from_edge, []).append(state_idx)
            edge_to_first_lane.setdefault(from_edge, from_lane)

        approaches: list[dict] = []
        for edge_id, indices in edge_to_indices.items():
            lane_id = edge_to_first_lane[edge_id]
            angle_deg = 0.0
            try:
                shape = conn.lane.getShape(lane_id)
                if len(shape) >= 2:
                    # Direction at junction = last 2 shape points (lane points
                    # INTO the junction, so this is the approach direction).
                    p1 = shape[-2]
                    p2 = shape[-1]
                    # SUMO: +X east, +Y north. Compass: 0=N, 90=E, clockwise.
                    angle_rad = math.atan2(p2[0] - p1[0], p2[1] - p1[1])
                    angle_deg = (math.degrees(angle_rad) + 360.0) % 360.0
            except Exception:
                pass
            approaches.append({
                "angle_deg": round(angle_deg, 1),
                "link_indices": indices,
                "from_edge": edge_id,
            })
        approaches.sort(key=lambda a: a["angle_deg"])
        return {"approaches": approaches}

    def get_num_phases(self, tl_id: str | None = None) -> int:
        """Return the number of phases in the TL program."""
        conn = self._conn()
        tl_id = self._resolve_tl_id(tl_id)
        logic = conn.trafficlight.getAllProgramLogics(tl_id)
        if logic:
            return len(logic[0].phases)
        return 0

    def install_fixed_time_program(
        self,
        green_duration: int = 35,
        yellow_duration: int = 3,
        tl_id: str | None = None,
    ) -> None:
        """Install a fixed-time TLS program for baseline comparison.

        Creates a 4-phase program:
          Phase 0: NS green, EW red  (green_duration s)
          Phase 1: NS yellow, EW red (yellow_duration s)
          Phase 2: NS red, EW green  (green_duration s)
          Phase 3: NS red, EW yellow (yellow_duration s)
        """
        conn = self._conn()
        tl_id = self._resolve_tl_id(tl_id)

        # Get current program to understand the link count
        current = conn.trafficlight.getAllProgramLogics(tl_id)
        if not current:
            raise RuntimeError("No TLS program found")

        num_links = len(current[0].phases[0].state)

        # Build simple 2-axis fixed program
        # For a 4-arm intersection with 2 lanes each:
        #   The state string encodes each controlled link.
        #   We use the existing state length and create a simple
        #   NS-green / EW-green alternation.

        # Get the green phases from the existing program
        # We'll create our own simple program
        half = num_links // 2

        # Phase 0: first half green, second half red
        ns_green = "G" * half + "r" * (num_links - half)
        ns_yellow = "y" * half + "r" * (num_links - half)
        # Phase 2: first half red, second half green
        ew_green = "r" * half + "G" * (num_links - half)
        ew_yellow = "r" * half + "y" * (num_links - half)

        phases = [
            traci.trafficlight.Phase(green_duration, ns_green),
            traci.trafficlight.Phase(yellow_duration, ns_yellow),
            traci.trafficlight.Phase(green_duration, ew_green),
            traci.trafficlight.Phase(yellow_duration, ew_yellow),
        ]

        logic = traci.trafficlight.Logic(
            "fixed_baseline", 0, 0, phases=phases,
        )

        conn.trafficlight.setProgramLogic(tl_id, logic)
        conn.trafficlight.setProgram(tl_id, "fixed_baseline")
        logger.info(
            "Installed fixed-time program: %ds green / %ds yellow",
            green_duration,
            yellow_duration,
        )

    def get_network_geometry(self) -> dict:
        """Extract network geometry for frontend visualization.

        Returns junction positions, edge shapes, and lane shapes so the
        frontend can render the road network on a canvas.
        """
        conn = self._conn()

        # Junctions
        junctions = []
        for jid in conn.junction.getIDList():
            if jid.startswith(":"):
                continue  # skip internal junctions
            pos = conn.junction.getPosition(jid)
            junctions.append({
                "id": jid,
                "x": pos[0],
                "y": pos[1],
            })

        # Edges and lanes
        edges = []
        for eid in conn.edge.getIDList():
            if eid.startswith(":"):
                continue
            num_lanes = conn.edge.getLaneNumber(eid)
            lanes = []
            for i in range(num_lanes):
                lane_id = f"{eid}_{i}"
                try:
                    shape = conn.lane.getShape(lane_id)
                    lanes.append({
                        "id": lane_id,
                        "shape": [{"x": p[0], "y": p[1]} for p in shape],
                    })
                except Exception:
                    pass
            if lanes:
                edges.append({
                    "id": eid,
                    "lanes": lanes,
                })

        return {"junctions": junctions, "edges": edges}

    def get_connection(self):
        """Expose the active TraCI connection (advanced usage)."""
        return self._conn()

    # ── Internal ──────────────────────────────────────────────────────

    def _conn(self):
        """Get the TraCI connection, raising if not running."""
        if not self._running:
            raise RuntimeError(f"SUMO [{self._label}] is not running")
        return traci.getConnection(self._label)
